kdmgmt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('member.urls')),
    url(r'^admin/', admin.site.urls),
]

member/urls.py
from django.conf.urls import url

from . import views

app_name='member'
urlpatterns = [
    url(r'^login$', views.do_login, name='login'),
    url(r'^logout/$', views.do_logout, name='logout'),

    url(r'^member/$', views.MemberListView.as_view(), name='index'),
    url(r'^member/(?P<pk>[0-9]+)/$', views.MemberDetailView.as_view(), name='detail'),

    url(r'^$', views.group_list_view, name='group_list'),
    url(r'^group/(?P<pk>[0-9]+)/$', views.group_detail_view, name='group_detail'),

    url(r'^group/(?P<group_id>[0-9]+)/csv/$', views.export_group_to_csv, name='csv_export'),
]

member/models.py
from django.contrib.auth.backends import UserModel
from django.db import models


# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(UserModel)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Member(models.Model):
    name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    birth_date = models.DateField()
    gender = models.CharField(max_length=1, choices=(("m", "male"), ("f", "female")))
    grade = models.CharField(max_length=10, null=True, blank=True, choices=[
        ("6K", "6. Kyu"),
        ("5K", "5. Kyu"),
        ("4K", "4. Kyu"),
        ("3K", "3. Kyu"),
        ("2K", "2. Kyu"),
        ("1K", "1. Kyu"),
        ("1D", "1. Dan"),
        ("2D", "2. Dan"),
        ("3D", "3. Dan"),
        ("4D", "4. Dan"),
        ("5D", "5. Dan"),
        ("6D", "6. Dan"),
        ("7D", "7. Dan"),
        ("8D", "8. Dan")
    ])
    email = models.EmailField()
    club = models.CharField(max_length=100, null=True, blank=True)
    zekken = models.BooleanField()
    jacket = models.BooleanField()
    joined = models.DateField(null=True, blank=True)
    group = models.ManyToManyField(Group)

member/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic

# Create your views here.
from .models import Member, Group


@login_required
def export_group_to_csv(request, group_id):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="kader.csv"'

    # The data is hard-coded here, but you could load it from a database or
    # some other source.
    group = Group.objects.get(pk=group_id)
    csv_data = group.member_set.all().order_by('name')

    t = loader.get_template('member/csv.txt')
    c = {
        'data': csv_data,
    }
    response.write(t.render(c))
    return response


def do_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('member:group_list'))
        else:
            return redirect(reverse('member:login'))
    else:
        return render(request, 'login.html')


def do_logout(request):
    logout(request)
    return redirect(reverse('member:login'))


class MemberListView(LoginRequiredMixin, generic.ListView):
    template_name = 'member/list.html'
    context_object_name = 'members'
    login_url = reverse_lazy('member:login')

    def get_queryset(self):
        return Member.objects.order_by('name')


class MemberDetailView(LoginRequiredMixin, generic.DetailView):
    model = Member
    template_name = 'member/detail.html'
    login_url = reverse_lazy('member:group_list')


@login_required
def group_list_view(request):
    groups = Group.objects.filter(users__id=request.user.id).order_by('name')
    return render(request, 'group/list.html', {'groups': groups})


@login_required
def group_detail_view(request, pk):
    group = get_object_or_404(Group, pk=pk, users__id=request.user.id)
    return render(request, 'group/detail.html', {'group': group})

member/templates/group/detail.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2>{{ group.name }}</h2>
    </div>
    <div class="col-md-12 text-right">
        <a href="{% url 'member:csv_export' group.id %}">csv</a>
    </div>
    <div class="col-md-12">
        <table class="table col-md-12 table-striped">
            <tr>
                <th class="col-md-1">Name</th>
                <th class="col-md-1">Birthdate</th>
                <th class="col-md-1">Gender</th>
                <th class="col-md-1">Grade</th>
                <th class="col-md-1">Email</th>
                <th class="col-md-1">Club</th>
                <th class="col-md-1">Zekken</th>
                <th class="col-md-1">Jacket</th>
                <th class="col-md-1">Joindate</th>
            </tr>
            {% for member in group.member_set.all %}
            <tr>
                <td class="col-md-1"><a href="{% url 'member:detail' member.id %}">{{ member.name }}
                    {{ member.first_name }}</a></td>
                <td class="col-md-1">{{ member.birth_date }}</td>
                <td class="col-md-1">{{ member.gender }}</td>
                <td class="col-md-1">{{ member.grade }}</td>
                <td class="col-md-1">{{ member.email }}</td>
                <td class="col-md-1">{{ member.club }}</td>
                <td class="col-md-1"><input name="checkbox_name" id="zekken" type="checkbox" disabled="disabled"
                                            {% if member.zekken %} checked="checked"{% endif %}></td>
                <td class="col-md-1"><input name="checkbox_name" id="jacket" type="checkbox" disabled="disabled"
                                            {% if member.jacket %} checked="checked"{% endif %}></td>
                <td class="col-md-1">{{ member.joined }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

member/templates/group/list.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Groups</h1>
    </div>
    <div class="col-md-12">
        <ul>
            {% if groups %}
            {% for group in groups %}
                <li>
                    <a href="{% url 'member:group_detail' group.id %}">{{ group.name }}</a>
                </li>
            {% endfor %}
            {% else %}
            <p>No groups are available.</p>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

member/templates/layout.html
<!DOCTYPE html>
{# Load the tag library #}
{% load bootstrap3 %}

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_javascript jquery=1%}
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid" id="navfluid">
        <div class="navbar-header">
            <button class="navbar-toggle" data-target="#navigationbar" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand"><a href="{% url 'member:group_list' %}" title="List">KD Manager</a></span>
        </div>
        <div class="navbar-collapse collapse" id="navigationbar">
            <ul class="nav navbar-nav">
                {% if user.is_staff %}
                <li>
                    <a href="{% url 'admin:index' %}" title="Admin">Admin</a>
                </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <p class="nav navbar-text navbar-right">{{ user.username }} -&nbsp;</p>
                </li>
                {% endif %}
                <li>
                    {% if user.is_authenticated %}
                    <a href="{% url 'member:logout' %}" title="Logout">Logout</a>
                    {% else %}
                    <a href="{% url 'member:login' %}" title="Login">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

member/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<div class="col-md-4"></div>
<div class="col-md-4">
    <form class="form-signin" method="POST" action="{% url 'member:login' %}">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputUser" class="sr-only">Email address</label>
        <input name="username" type="text" id="inputUser" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>
<div class="col-md-4"></div>
{% endblock %}

member/templates/member/detail.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2>{{ member.name }}, {{ member.first_name }}</h2>
        <table>
            <tr>
                <td class="col-md-3">Birthdate:</td>
                <td>{{ member.birth_date }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Gender:</td>
                <td>{{ member.gender }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Grade:</td>
                <td>{{ member.grade }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Email:</td>
                <td>{{ member.email }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Email:</td>
                <td>{{ member.email }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Club:</td>
                <td>{{ member.club }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Zekken:</td>
                <td><input name="zekken" id="zekken" type="checkbox" disabled="disabled"
                                   {% if member.zekken %} checked="checked" {% endif %}></td>
            </tr>
            <tr>
                <td class="col-md-3">Jacket:</td>
                <td><input name="jacket" id="jacket" type="checkbox" disabled="disabled"
                           {% if member.jacket %} checked="checked" {% endif %}></td>
            </tr>
            <tr>
                <td class="col-md-3">Joined:</td>
                <td>{{ member.joined }}</td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}

member/templates/member/layout.html
<!DOCTYPE html>
{# Load the tag library #}
{% load bootstrap3 %}

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_javascript jquery=1%}
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
</head>

<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid" id="navfluid">
        <div class="navbar-header">
            <button class="navbar-toggle" data-target="#navigationbar" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand"><a href="{% url 'member:index' %}" title="List">KD Manager</a></span>
        </div>
        <div class="navbar-collapse collapse" id="navigationbar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'admin:index' %}" title="Admin">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

member/templates/member/list.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Members</h1>
    </div>
    <div class="col-md-12 text-right">
        <a href="{% url 'member:csv_export' %}">csv</a>
    </div>
    <div class="col-md-12">
        <table class="table col-md-12 table-striped">
            <tr>
                <th class="col-md-1">Name</th>
                <th class="col-md-1">Birthdate</th>
                <th class="col-md-1">Gender</th>
                <th class="col-md-1">Grade</th>
                <th class="col-md-1">Email</th>
                <th class="col-md-1">Club</th>
                <th class="col-md-1">Zekken</th>
                <th class="col-md-1">Jacket</th>
                <th class="col-md-1">Joindate</th>
            </tr>
            {% if members %}
            {% for member in members %}
            <tr>
                <td class="col-md-1"><a href="{% url 'member:detail' member.id %}">{{ member.name }}
                    {{ member.first_name }}</a></td>
                <td class="col-md-1">{{ member.birth_date }}</td>
                <td class="col-md-1">{{ member.gender }}</td>
                <td class="col-md-1">{{ member.grade }}</td>
                <td class="col-md-1">{{ member.email }}</td>
                <td class="col-md-1">{{ member.club }}</td>
                <td class="col-md-1"><input name="checkbox_name" id="zekken" type="checkbox" disabled="disabled"
                                            {% if member.zekken %} checked="checked"{% endif %}></td>
                <td class="col-md-1"><input name="checkbox_name" id="jacket" type="checkbox" disabled="disabled"
                                            {% if member.jacket %} checked="checked"{% endif %}></td>
                <td class="col-md-1">{{ member.joined }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <p>No members are available.</p>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}

member/templates/member/member_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Members</h1>
    </div>
    <div class="col-md-12 text-right">
        <a href="{% url 'member:csv_export' %}">csv</a>
    </div>
    <div class="col-md-12">
        <table class="table col-md-12 table-striped">
            <tr>
                <th class="col-md-1">Name</th>
                <th class="col-md-1">Birthdate</th>
                <th class="col-md-1">Gender</th>
                <th class="col-md-1">Grade</th>
                <th class="col-md-1">Email</th>
                <th class="col-md-1">Club</th>
                <th class="col-md-1">Zekken</th>
                <th class="col-md-1">Jacket</th>
                <th class="col-md-1">Joindate</th>
            </tr>
            {% if members %}
            {% for member in members %}
            <tr>
                <td class="col-md-1"><a href="{% url 'member:detail' member.id %}">{{ member.name }}
                    {{ member.first_name }}</a></td>
                <td class="col-md-1">{{ member.birth_date }}</td>
                <td class="col-md-1">{{ member.gender }}</td>
                <td class="col-md-1">{{ member.grade }}</td>
                <td class="col-md-1">{{ member.email }}</td>
                <td class="col-md-1">{{ member.club }}</td>
                <td class="col-md-1"><input name="checkbox_name" id="zekken" type="checkbox" disabled="disabled"
                                            {% if member.zekken %} checked="checked"{% endif %}></td>
                <td class="col-md-1"><input name="checkbox_name" id="jacket" type="checkbox" disabled="disabled"
                                            {% if member.jacket %} checked="checked"{% endif %}></td>
                <td class="col-md-1">{{ member.joined }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <p>No members are available.</p>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}